### ISSUE TITLE
"TwainDotNet.TwainException" en TwainDotNet.dll

### ISSUE THREAD

**Issue by carlospas** [sourcesachin/Twain-Web-Server#1]
Please help me i training to run in visual studios 2015 and set x86 but has one error 
Unhandled exception of type  'TwainDotNet.TwainException' en TwainDotNet.dll
....-................................................
public Scaner()
        {
            InitializeComponent();
            _twain = new Twain(new WinFormsWindowMessageHook(this));  <---------------------------------------
.....................................................................
what can I do? please help me!

![Captura](https://user-images.githubusercontent.com/43582884/152614482-def87c95-259f-4811-b727-2f770a8db697.PNG)

**Comment by sourcesachin** [comment]
Please add below assembly in References. those are present in bin/debug folder.
TwainDotNet.WinFroms.dll
TwainDotNet.dll
